project:
  type: book
  output-dir: _output
book:
  title: "DMA818 — Boston Housing Analysis"
  author: "Edward Solomon Kweku Gyimah (SE/DAT/24/0007)"
  date: today
  chapters:
    - index.qmd
format:
  html:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
