[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"
select = ["E","F","I","B","UP","ICN","ARG","SIM","C4","PL","NPY"]
ignore = [
  "E203",  # black compatibility on slice spacing
]
[tool.ruff.isort]
known-first-party = ["streamlit_app"]
profile = "black"
